### ISSUE TITLE
list xs option

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#10]
можно сделать более компактный вид используя .push .pull и смену позиций блока
изменения касаются трех строчек (файл приложен)

5 строка 
до  `<div class="col-xs-12 col-sm-3">`
после  `<div class="col-xs-6 col-sm-3">`

168 строка  
до  `<div class="col-xs-12 col-sm-3 text-center">`
после   `<div class="col-xs-6 col-sm-3 col-sm-push-6 text-center">`

87 строка
до   `<div class="col-xs-12 col-sm-6">`
после  `<div class="col-xs-12 col-sm-6 col-sm-pull-3">`

блоки **Name and URL of the product** меняются местами с **Price the product**
![list](https://user-images.githubusercontent.com/31338643/33243473-e24df350-d2f7-11e7-8a51-ccd8e080bdf5.jpg)
**измененный list.tpl**
[list.zip](https://github.com/JKassa/jkTemplatesBootstrap3/files/1504158/list.zip)

**Comment by GeneticsPro** [comment]
Вы можете показать полный код файла list.tpl?

**Comment by ivan-nagaev** [comment]
**в конце прошлого сообщения list.zip**

<ul class="list-unstyled list-products">

  {% for product in products %}

  <li class="row" itemtype="http://schema.org/Product" itemscope>

    

    <div class="col-xs-6 col-sm-3">

      <div class="product-image">

        

        {% if product.stickers %}

        

        <ul class="stickers">

          {% if product.new %}

          <li>

            <span class="product-label product-label_new">NEW</span>

          </li>

          {% endif %}

          {% if product.hit %}

          <li>

            <span class="product-label product-label_hit">HIT</span>

          </li>

          {% endif %}

          {% if product.discount %}

          <li>

            {% assign options = 'decimals' | arrayCombine: 0 %}

            {% if product.discount_image %}

            <img {{ product.discount_image | img_exists: '30x30' }} alt="" title="{{ product.discount_desc }} - {{ product.discount | costDisplay: options }}{{ product.d_symbol }}">

            {% else %}

            <span class="product-label" title="{{ product.discount_desc }} - {{ product.discount | costDisplay: options }}{{ product.d_symbol }}">

              -{{ product.discount | costDisplay: options }}{% if product.d_symbol == '%' %}{{ product.d_symbol }}{% endif %}

            </span>

            {% endif %}

          </li>

          {% endif %}

        </ul>

        {% endif %}

        

        {% if product.manufacturer %}

        

        <div style="position: absolute; right:0; top:0;" itemtype="http://schema.org/Brand" itemscope itemprop="brand">

          <span style="display: none;" itemprop="name">{{ product.manufacturer.name }}</span>

          <img {{ product.manufacturer.thumbnail | img_exists: '30x30' }} class="manufacturer hasTooltip" itemprop="logo" alt="{{ product.manufacturer.alias }}" title="{{ product.manufacturer.name }}">

        </div>

        {% endif %}

        

        {% if product.tags %}

        

        <div style="position: absolute; right: 0; bottom: 4px">

          {% for tag in product.tags %}

          <a href="{{ tag.url }}" class="{{ tag.link_class }}" style="float: right; border-radius: 9px 0 0 9px; margin-top: 2px">

            {{ tag.title }}

          </a><br>

          {% endfor %}

        </div>

        {% endif %}

        

        

        <div class="text-center">

          <a href="{{ product.url }}" target="_top">

            <img {{ product.image | img_exists: '104x150' }} alt="{{ product.alias }}" style="max-width: 100%; max-height: {{ img_height }}px;" />

          </a>

        </div>

        

        

        {% capture selector_quick_view %}jk-quick_view-{{ product.id }}{% endcapture %}

        <div class="quick-view">

          <a href="#" data-click="show-modal" data-id="{{ selector_quick_view }}" data-src="{{ product.quick_url }}" class="btn btn-default jk-quick_view" title="{{ 'sprintf' | jtext: 'COM_JKASSA_QUICK_VIEW_TITLE', product.name }}">

            <span class="glyphicon glyphicon-zoom-in"></span>

            {{ '_' | jtext: 'COM_JKASSA_QUICK_VIEW' }}

          </a>

        </div>

        

        {% if product.present %}

        

        <div class="share hasTooltip" title="{{ 'tooltipText' | jhtml: product.present.name, product.present.desc }}">

          <div class="sharetitle">

            {{ '_' | jtext: 'COM_JKASSA_GIFT' }}

          </div>

          <div class="sharedesc">

            <a href="{{ product.present.url }}" target="_top">

              <img {{ product.present.image | img_exists: '50x50' }} alt="{{ product.present.name }}">

            </a>

          </div>

        </div>

        {% endif %}

      </div>

    </div>


    <div class="col-xs-6 col-sm-3 col-sm-push-6 text-center">

      

      <div class="m-t-10" itemprop="offers" itemscope itemtype="http://schema.org/Offer">

        

        {% if product.old_cost %}

        <del class="text-muted">{{ product.old_cost | costDisplay }}{{ currency.symbol }}</del>

        <br>

        {% endif %}



        

        <span class="cost">

          <meta itemprop="priceCurrency" content="{{ currency.code }}" />

          {% assign options = 'dec_point,thousands_sep' | arrayCombine: '.', '*' %}

          <span itemprop="price" content="{{ product.cost | costDisplay: options }}">{{ product.cost | costDisplay }}</span>{{ currency.symbol }}

        </span>



        {% if product.discount %}

        <br>

        

        <small class="text-primary">

          {{ '_' | jtext: 'COM_JKASSA_DISCOUNT' }}:

          {{ product.discount | costDisplay }}{{ product.d_symbol }}

        </small>

        {% endif %}



    {% if product.vat %}

    <br>

    

      <span class="text-muted small">

      ({{ 'sprintf' | jtext: 'COM_JKASSA_VAT_INCL', product.vat }})

    </span>

        {% endif %}

      </div>



    {% if show_stock %}

      

      <div class="m-t-10 text-muted">

        {% case product.stock %}

        {% when 0 %}

        

        {{ '_' | jtext: 'COM_JKASSA_STOCK_0' }}

        {% when '-1' %}

        

        {{ '_' | jtext: 'COM_JKASSA_STOCK_1' }}

        {% when '-2' %}

        

        {{ '_' | jtext: 'COM_JKASSA_STOCK_2' }}

        {% else %}

        

        {{ '_' | jtext: 'COM_JKASSA_STOCK' }}: {{ product.stock }}

        {% endcase %}

      </div>

    {% endif %}



      {% if product.cart_disabled != 'false' and show_quantity %}

      

      <div class="input-group qty-product m-t-10 m-b-0 col-xs-3 col-sm-7" style="margin: auto !important">

        <span class="input-group-btn">

          <a href="javascript:;" class="btn btn-default btn-sm" type="button" data-click="qty-minus" data-id="{{ product.id }}" title="{{ '_' | jtext: 'COM_JKASSA_QTY_BTN' }}">&minus;</a>

        </span>

        <input type="text" value="{{ product.limit }}" data-limit="{{ product.limit }}" data-maxlimit="{{ product.maxlimit }}" class="form-control input-sm text-center mw-45" name="qty-product-{{ product.id }}" title="{{ '_' | jtext: 'COM_JKASSA_QTY_TITLE' }}">

        <span class="input-group-btn">

          <a href="javascript:;" class="btn btn-default btn-sm" type="button" data-click="qty-plus" data-id="{{ product.id }}" title="{{ '_' | jtext: 'COM_JKASSA_QTY_BTN' }}">+</a>

        </span>

      </div>

      {% endif %}



      

      <div>

        <div class="m-t-10">

          

          {% if product.cart_disabled %}

          <span class="btn btn-sm btn-primary disabled" title="{{ product.cart_title }}">

            <span class="glyphicon glyphicon-shopping-cart"></span>

            {{ product.cart_text }}

          </span>

          {% else %}

          <a href="#" data-click="to-cart" data-id="{{ product.id }}" class="btn btn-sm btn-primary" title="{{ product.cart_title }}">

            <span class="glyphicon glyphicon-shopping-cart"></span>

            {{ '_' | jtext: 'COM_JKASSA_TO_CART' }}

          </a>

          {% endif %}

        </div>



        <div class="btn-group m-t-10">

          

          {% if product.wishlist_disabled %}

          <span class="btn btn-sm btn-danger disabled" title="{{ 'sprintf' | jtext: 'COM_JKASSA_ALREADY_WISHLIST', product.name }}">

            <span class="glyphicon glyphicon-heart"></span>

          </span>

          {% else %}

          <a href="#" data-click="to-wishlist" data-id="{{ product.id }}" class="btn btn-sm btn-danger" title="{{ 'sprintf' | jtext: 'COM_JKASSA_TO_WISHLIST_TITLE', product.name }}">

            <span class="glyphicon glyphicon-heart"></span>

          </a>

          {% endif %}



          

          {% if product.compare_disabled %}

          <span class="btn btn-sm btn-default disabled" title="{{ 'sprintf' | jtext: 'COM_JKASSA_COMPARE_ALREADY_ADDED', product.name }}">

            <span class="glyphicon glyphicon-random"></span>

          </span>

          {% else %}

          <a href="#" data-click="to-compare" data-id="{{ product.id }}" class="btn btn-default btn-sm" title="{{ 'sprintf' | jtext: 'COM_JKASSA_COMPARE_ADD_TITLE', product.name}}">

            <span class="glyphicon glyphicon-random"></span>

          </a>

          {% endif %}

        </div>

      </div>

    </div>


    <div class="col-xs-12 col-sm-6 col-sm-pull-3">

      

      <h4>

        <a href="{{ product.url }}" target="_top">

          <span itemprop="name">{{ product.name }}</span>

        </a>

        {% if product.files %}

        

        

        <span title="<strong>{{ '_' | jtext: 'COM_JKASSA_ATTACHMENT' }}:</strong><br>{{ product.files | join: '<br>' }}" class="hasTooltip">

          <span class="glyphicon glyphicon-download small"></span>

        </span>

        {% endif %}

      </h4>

      

      {% comment %}

		  Rating reviews JKassa or Plug-in voting (See: Plugin Manager: Plugins -> jkvotes).

	  {% endcomment %}

	  {% if reviews_included %}

	    

	    <div class="text-right" title="{{ 'plural' | jtext: 'COM_JKASSA_REVIEWS_COUNT', product.rating_count }}">

		  {% for i in (1..5) %}

		    {% if product.rating >= i %}

		    <span class="glyphicon glyphicon-star" style="color: #F2CD00"></span>

		    {% else %}

		    <span class="glyphicon glyphicon-star-empty" style="color: #CCCCCC"></span>

		    {% endif %}

		  {% endfor %}

	    </div>

	  {% else %}

	    {% assign votes = product.id | jkcountervotes: product.rating, product.rating_count %}

	    {% if votes %}

	    

	    <div class="text-right">

		  {{ votes }}

	    </div>

	    {% endif %}

	  {% endif %}

      

      

      <div class="text-muted small text-right">

        {{ '_' | jtext: 'COM_JKASSA_SKU' }}:

        <span itemprop="mpn">

          {{ product.sku }}

        </span>

      </div>

      

      

      <div itemprop="description">

        {{ product.introtext | truncateDesc: 140 }}

      </div>

      

      {% comment %}

          Variants product.

          See: html\forms\variants.tpl

      {% endcomment %}

      {% if product.variants %}

      <div>

        {{ product.variants }}

      </div>

      {% endif %}

      

      

      <div class="m-t-10">

        <a href="{{ product.url }}" class="btn btn-sm btn-default" title="{{ 'sprintf' | jtext: 'COM_JKASSA_READ_MORE', product.name }}" itemprop="url" target="_top">

          {{ '_' | jtext: 'JGLOBAL_DESCRIPTION' }} <span class="glyphicon glyphicon-circle-arrow-right"></span>

        </a>

        

        {% comment %}

            Connecting comments plugin.

            See: Plugin Manager: Plugins -> jkcomments.

        {% endcomment %}

        {% capture title_comments %}<span class="glyphicon glyphicon-comment"></span> [COUNT]{% endcapture %}

        {% assign count_comments = product.id | jkcountercomments: title_comments, product.url, 'btn btn-sm' %}

        

        {% if count_comments %}

        {{ count_comments }}

        {% endif %}

      </div>

    </div>

    

    

    {% comment %}

      Madal body for Quick view.

    {% endcomment %}

    {{ 'renderModal' | bootstrap3: selector_quick_view, 'modal-lg', product.name, '', '', true }}

  </li>

  {% endfor %}

</ul>

**Comment by GeneticsPro** [comment]
Прошу прощения, только сейчас увидел ссылку на архив: **измененный list.tpl**.

**Comment by GeneticsPro** [comment]
В версии 2.5.beta3 добавлено.
Спасибо.

**Comment by ghost** [comment]
нужен отступ 11 строка  `<div class="product-image m-t-20">`

![m-t-20](https://user-images.githubusercontent.com/31338643/33283167-0b25a63c-d3bc-11e7-89fa-7c06c63f66eb.jpg)

**Comment by GeneticsPro** [comment]
В 2.5.beta4 исправлено.
