### ISSUE TITLE
cart xs option

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#11]
../jktplbootstrap3/views/cart/default.tpl
**файл для анализа** [cart.zip](https://github.com/JKassa/jkTemplatesBootstrap3/files/1507646/cart.zip)

![cart](https://user-images.githubusercontent.com/31338643/33289884-04f2ee62-d3d2-11e7-8508-10c058f15aa4.jpg)

**Comment by GeneticsPro** [comment]
В 2.5.beta4 исправлено.
