### ISSUE TITLE
Sort by

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#12]
../jktplbootstrap3/html/products/default.tpl

**61 строка** 
до  `<div class="col-xs-8">`
после  `<div class="col-xs-12 col-sm-8">`
**89 строка** 
до  `<div class="col-xs-4 text-right">`
после  `<div class="col-xs-12 col-sm-4 text-right m-t-10">`

![1](https://user-images.githubusercontent.com/31338643/33337800-3beaa136-d485-11e7-9344-38b920eaa59f.jpg)

**Comment by GeneticsPro** [comment]
Я предлагаю вообще скрыть поле выбора количества элементов:

![09c63a5d21](https://dl3.joxi.net/drive/2017/11/29/0008/2887/535367/67/09c63a5d21.png)

**Comment by ghost** [comment]
я тоже думал об ограничении функционала в xs. согласен

**Comment by GeneticsPro** [comment]
В версии 2.5.beta5 исправлено.
