### ISSUE TITLE
nav nav-tabs

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#13]
../jktplbootstrap3/views/product/default.tpl

**747 строка** 
до  `<ul class="nav nav-tabs m-b-15" role="tablist">`
после  `<ul class="nav nav-tabs nav-justified m-b-15" role="tablist">`

![nav-tabs](https://user-images.githubusercontent.com/31338643/33344181-182239d0-d499-11e7-8a58-cd2b875dc1d7.jpg)

**Comment by GeneticsPro** [comment]
Спасибо, исправим.

**Comment by GeneticsPro** [comment]
В версии 2.5.beta5 исправлено.
