### ISSUE TITLE
img container-popup

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#14]
При добавлении изображения в карточке товара предлагаю увеличить размер области с изображениями (маленькое окошко не очень удобно).
но это же относится к самой joomla, как-то реализовать (переопределить) для jkassa может?

![img-3](https://user-images.githubusercontent.com/31338643/33426053-7b022518-d5b8-11e7-9c61-996a310aecb1.jpg)

../administrator/components/com_media/views/images/tmpl/default.php
[default.zip](https://github.com/JKassa/jkTemplatesBootstrap3/files/1517381/default.zip)

**../media/media/css/popup-imagemanager.css**
**до**  `iframe#imageframe {height: 200px;}`
**после**  `iframe#imageframe {height: 285px;}`

**../administrator/templates/isis/css/template.css**
**до**  `container-popup {padding: 28px 10px 10px 10px;}`
**после**  `container-popup {padding: 10px 10px 10px 10px;}`

**Comment by GeneticsPro** [comment]
Это не относится к теме jkTemplatesBootstrap3.
И к JKassa вообще.
С этой проблемой вам сюда - https://github.com/joomla/joomla-cms
