### ISSUE TITLE
<!--More products-->

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#2]
/html/products/block.tpl   252 строка
`<li class="col-xs-{{ col_xs }}">`
![more-products](https://user-images.githubusercontent.com/31338643/33185822-49dfe7c6-d096-11e7-91da-96efaf2de6fe.jpg)

вернее будет `<li class="col-sm-{{ col_xs }} col-xs-12">`

**Comment by GeneticsPro** [comment]
Тут тоже будет:
```
<!--More products-->
<li class="col-xs-12 col-sm-6 col-md-{{ col_md }}">
```
