### ISSUE TITLE
block-products

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#3]
.../html/products/block.tpl
4 строка
![block-products](https://user-images.githubusercontent.com/31338643/33187223-50d9f250-d0a1-11e7-8196-185be50489fe.jpg)

вернее будет  `<li class="col-sm-{{ col_xs }} col-xs-12" itemscope itemtype="http://schema.org/Product">`

откуда берет значение переменная {{ col_sm }} ?

**Comment by GeneticsPro** [comment]
/views/category/block.tpl

```
{% assign col_xs = tpl_params.col_xs | default_value: 4 %}
{% assign col_sm = col_xs | times: 2 %}
```

**Comment by GeneticsPro** [comment]
Вот такой вариант оставим:
`<li class="col-xs-12 col-sm-6 col-md-{{ col_md }}" itemscope itemtype="http://schema.org/Product">`

**Comment by ghost** [comment]
не пойму почему col-md-**{{ col_md }}** ?
насколько я понял пользовательские данные введенные в шаблоне "блоков в строке" присваиваются переменной {{ col_xs }}. следовательно будет col-md-{{ col_xs }}.
{{ col_md }} - вроде как вообще не определена

или я ошибаюсь?

**Comment by GeneticsPro** [comment]
В новой версии изменены некоторые имена переменных.
Файл config.json:
"name":"p_in_row" и "name":"f_in_row".
Файл: /views/category/block.tpl:
{% assign col_md = tpl_params.p_in_row | default_value: 4 %}
