### ISSUE TITLE
wishlist xs devices

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#6]
![wishlist](https://user-images.githubusercontent.com/31338643/33232189-a25f3050-d212-11e7-9878-67f345420c3d.jpg)

**Comment by GeneticsPro** [comment]
По поводу диалогового окна смотрите - https://github.com/JKassa/jkTemplatesBootstrap3/issues/9

В версии 2.5.beta2 исправлено:

![Список желаний](https://dl4.joxi.net/drive/2017/11/27/0008/2887/535367/67/06cb97b1f5.png)
