### ISSUE TITLE
compare xs, sm devices

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#7]
- было бы не плохо для удобства читаемости добавить таблице **.table-striped**
- выравнивание просится по центру
- при маленьком разрешении в таблицу с трудом влазит 2 сравниваемых продукта

![compare](https://user-images.githubusercontent.com/31338643/33232331-82938dd6-d215-11e7-9f7b-29c14d5325cb.jpg)

**Comment by GeneticsPro** [comment]
По поводу диалогового окна смотрите - https://github.com/JKassa/jkTemplatesBootstrap3/issues/9

В версии 2.5.beta2 добавлено:
**table-striped** и **table-responsive**.

![Сравнение продуктов](https://dl3.joxi.net/drive/2017/11/27/0008/2887/535367/67/767b28492e.png)
