### ISSUE TITLE
quick view

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#8]
при маленьком разрешении считаю быстрый просмотр не нужен, т.к. выход из него затруднителен. на изображении изобразил то расстояние, между красной и синей линиями, на которое нужно нажать чтобы выйти, либо положить товар в корзину. если уже оставлять то надо крестик (.close).
![quick-view](https://user-images.githubusercontent.com/31338643/33232541-2e4e7110-d219-11e7-91c7-15d4c18e14bb.jpg)

**Comment by GeneticsPro** [comment]
В версии 2.5.beta2 добавлено к кнопке: **hidden-xs**.
