### ISSUE TITLE
jk_alert_dialog  cart_xs

### ISSUE THREAD

**Issue by ghost** [JKassa/jkTemplatesBootstrap3#9]
![cart_xs](https://user-images.githubusercontent.com/31338643/33232652-d3fdbdb8-d21a-11e7-97fe-ca009e8b9e7c.jpg)

**Comment by GeneticsPro** [comment]
В версии 2.5.beta2 исправлено:

![jk_alert_dialog-1](https://dl4.joxi.net/drive/2017/11/27/0008/2887/535367/67/958d15d660.png)

![jk_alert_dialog-1](https://dl3.joxi.net/drive/2017/11/27/0008/2887/535367/67/e0a4dc75ba.png)
